site_name: Ian Edmundson - Portfolio
site_url: https://ianedmundson1.github.io
site_author: Ian Edmundson
site_description: Data Scientist & Software Engineer Portfolio
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

#This adds a GitHub icon to the header
repo_url: https://github.com/ianedmundson1/ianedmundson.github.io
repo_name: GitHub 

# filepath: /home/edmundsonim/github/ianedmundson.github.io/mkdocs.yml
plugins:
  - search
  - include-markdown
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "docs.scripts.fetch_readme:fetch_readme"

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md
      - Computer Vision:
          - Overview: projects/computer-vision/index.md
          - Facial Detection: projects/computer-vision/facial-detection/README.md
          - Lane Detection: projects/computer-vision/lane-detection/README.md
          - Security Camera: projects/computer-vision/security-camera/README.md
      - Data Science:
          - Overview: projects/data-science/index.md
          - MIT Applied Data Science: projects/data-science/mit-applied-data-science/README.md
  - Books: 
      - Overview: books/index.md
      - Reviews:
          - Designing Machine Learning Systems: books/reviews/Book-Recommendations/Designing-machine-learning-systems/book_review.md
          - Graph-Powered Machine Learning: books/reviews/Book-Recommendations/graph-powered-machine-learning/book_review.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ianedmundson1
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ian-edmundson-a0979a178